/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2015-01-01 07:14:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.ecommerce;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.sgnbs.system.beans.AdminBean;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/views/ecommerce/type.json", Long.valueOf(1420091663000L));
    _jspx_dependants.put("/WEB-INF/views/ecommerce/header_right.jsp", Long.valueOf(1420091663000L));
    _jspx_dependants.put("/WEB-INF/views/ecommerce/header.jsp", Long.valueOf(1420096423000L));
    _jspx_dependants.put("/WEB-INF/views/ecommerce/footer.jsp", Long.valueOf(1420091663000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<title>Software Store - Login</title>\r\n");
      out.write("<meta name=\"keywords\"\r\n");
      out.write("\tcontent=\"symbol box,software store, free template, ecommerce, online shop\" />\r\n");
      out.write("<meta name=\"description\"\r\n");
      out.write("\tcontent=\"symbol box,software store, free template, ecommerce, online shop \" />\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/css/ecommerce/default.css\" />\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/ecommerce/jquery-1.7.2.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"/js/ecommerce/jquery.flexslider-min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t//$.get(\"/ecommerce/header_right.jsp\", function(data) {\r\n");
      out.write("\t\t//\t$(\"#header_right\").html(data);\r\n");
      out.write("\t\t//});\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tfunction loginSubmit() {\r\n");
      out.write("\r\n");
      out.write("\t\tif (!checkvalue()) {\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar c = {\r\n");
      out.write("\t\t\tusername : $(\"#usernametxt\").attr(\"value\"),\r\n");
      out.write("\t\t\tpassword : $(\"#passwordtxt\").attr(\"value\"),\r\n");
      out.write("\t\t\tverifyCode : $(\"#verifycodetxt\").attr(\"value\")\r\n");
      out.write("\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\t$.post(\"/account/login_submit\", c, loginAjaxSuccess, \"json\");\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction loginAjaxSuccess(data) {\r\n");
      out.write("\t\tconsole.log(data);\r\n");
      out.write("\t\tvar member = data;\r\n");
      out.write("\r\n");
      out.write("\t\tif (member.error == \"nofulldata\") {\r\n");
      out.write("\t\t\talert(\"full data please\");\r\n");
      out.write("\t\t} else if (member.error == \"verifyCode\") {\r\n");
      out.write("\t\t\talert(\"wrong verify code\");\r\n");
      out.write("\t\t\t$(\"#verifycodetxt\").attr(\"value\", \"\");\r\n");
      out.write("\t\t\t$(\"#verifycodetxt\").focus();\r\n");
      out.write("\t\t} else if (member.error == \"nocustomer\") {\r\n");
      out.write("\t\t\talert(\"username doesn't exsit\");\r\n");
      out.write("\t\t\t$(\"#usernametxt\").attr(\"value\", \"\");\r\n");
      out.write("\t\t\t$(\"#passwordtxt\").attr(\"value\", \"\");\r\n");
      out.write("\t\t\t$(\"#verifycodetxt\").attr(\"value\", \"\");\r\n");
      out.write("\t\t\t$(\"#usernametxt\").focus();\r\n");
      out.write("\t\t} else if (member.error == \"notnormalstatus\") {\r\n");
      out.write("\t\t\talert(\"customer is forbiden\");\r\n");
      out.write("\t\t} else if (member.error == \"wrongpassword\") {\r\n");
      out.write("\t\t\talert(\"password is wrong\");\r\n");
      out.write("\t\t\t$(\"#passwordtxt\").attr(\"value\", \"\");\r\n");
      out.write("\t\t\t$(\"#verifycodetxt\").attr(\"value\", \"\");\r\n");
      out.write("\t\t\t$(\"#passwordtxt\").focus();\r\n");
      out.write("\t\t} else if (member.success == \"success\") {\r\n");
      out.write("\t\t\talert(\"Welcome to symbolbox !\");\r\n");
      out.write("\t\t\twindow.location.href = \"/myaccount\";\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\talert(\"unknow\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"#verifycodeimage\").click();\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction checkvalue() {\r\n");
      out.write("\t\tvar username = $(\"#usernametxt\").attr(\"value\");\r\n");
      out.write("\t\tvar password = $(\"#passwordtxt\").attr(\"value\");\r\n");
      out.write("\t\tvar verifycode = $(\"#verifycodetxt\").attr(\"value\")\r\n");
      out.write("\t\tif (username == null || username == \"\") {\r\n");
      out.write("\t\t\talert(\"put in username please\");\r\n");
      out.write("\t\t\t$(\"#usernametxt\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t} else if (password == null || password == \"\") {\r\n");
      out.write("\t\t\talert(\"put in password please\");\r\n");
      out.write("\t\t\t$(\"#passwordtxt\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t} else if (verifycode == null || verifycode == \"\") {\r\n");
      out.write("\t\t\talert(\"put in verifycode please\");\r\n");
      out.write("\t\t\t$(\"#verifycodetxt\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction keyLogin() {\r\n");
      out.write("\t\tif (event.keyCode == 13) {\r\n");
      out.write("\t\t\tloginSubmit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body onkeyup=\"keyLogin()\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"wrap\">\r\n");
      out.write("\t\t");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"/css/ecommerce/top_menu.css\" />\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/ecommerce/getsidebarlist.js\"></script>\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("\t<div class=\"header_nav\">\r\n");
      out.write("\t\t<div class=\"left_logo float_l\"></div>\r\n");
      out.write("\t\t<div class=\"right_nav float_r\">\r\n");
      out.write("\t\t\t<div class=\"login-search\" id=\"header_right\">");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	response.setHeader("Cache-Control", "no-cache"); //HTTP 1.1 
	response.setHeader("Pragma", "no-cache"); //HTTP 1.0 
	response.setDateHeader("Expires", 0); //prevents caching at the proxy server 
	AdminBean adminBean = (AdminBean) session.getAttribute("adminBean");
	StringBuffer jsp = new StringBuffer("<ul>");
	if (adminBean != null) {
		String useradmin = adminBean.getUsername();
		jsp.append("<li>");
		jsp.append("Welcome back:");
		jsp.append(useradmin);
		jsp.append("</li>");
		jsp.append("<li><a href=\"/myaccount\">My Account</a></li>");
		jsp.append("<li><a href=\"/myaccount?menuname=mycart\">My Cart</a></li>");
		jsp.append("<li><a href=\"/account/exist_submit\">Safety exit</a></li>");
	} else {
		jsp.append("<li>Welcome to SymbolBox,Please <a href=\"/login\">Login</a> or <a href=\"/register\">Register</a></li>");
	}
	jsp.append("</ul>");
	out.println(jsp.toString());

      out.write('\r');
      out.write('\n');
      out.write("</div>\r\n");
      out.write("\t\t\t<div class=\"cleaner\"></div>\r\n");
      out.write("\t\t\t<div class=\"menu\" id=\"menu\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/index\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"top_menu_list item\" id=\"top_menu_list_products\"><a\r\n");
      out.write("\t\t\t\t\t\thref=\"/product/product/query_detail.action\">Products</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/ordersymbol\">Order symbol</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/designhouse\">Design House</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/support\">Support</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/aboutus\">About us</a></li>\r\n");
      out.write("\t\t\t\t\t<!-- <li style=\"width: 150px;\">\r\n");
      out.write("\t\t\t\t\t\t<form method=\"post\" action=\"/typeparam/typeparam/mod_valid.action\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"nameSearch\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:searchSubmits()\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"float: right; margin-top: 12px;\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"/images/ecommerce/icon_search.png\"></img></a> <input\r\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"text\" value=\"\" name=\"model.namelike\" id=\"typeName\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width: 120px; float: right; margin-top: 16px;\" />\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</li> -->\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"cleaner\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tgetTopList(\r\n");
      out.write("{\r\n");
      out.write("\t\"CPLD\":{\"Xilinx\":{\"CoolRunner\":\"83\",\"faefef\":\"84\"},\"dgasdg\":{\"asdgsdg\":\"83\",\"vczxvcx\":\"84\"},\"Lattice\":{\"MachXO\":\"79\",\"MachXO2\":\"80\",\"4000ZE\":\"78\"},\"dgasdg\":{\"asdgsdg\":\"83\",\"vczxvcx\":\"84\"},\"Altera\":{\"MAXV\":\"76\",\"MAXII\":\"75\",\"MAX3000A\":\"74\"}},\r\n");
      out.write("\t\"gagadg\":{\"gasggdag\":{\"eagawe\":\"83\",\"asdf\":\"84\",\"asdgsdg\":\"83\",\"vczxvcx\":\"84\"},\"Lattice\":{\"MachXO\":\"79\",\"MachXO2\":\"80\",\"4000ZE\":\"78\"},\"Altera\":{\"MAXV\":\"76\",\"MAXII\":\"75\",\"MAX3000A\":\"74\"}},\r\n");
      out.write("\t\"asdsdg\":{\"dgasdg\":{\"asdgsdg\":\"83\",\"vczxvcx\":\"84\"},\"Lattice\":{\"MachXO\":\"79\",\"MachXO2\":\"80\",\"4000ZE\":\"78\"},\"Altera\":{\"MAXV\":\"76\",\"MAXII\":\"75\",\"MAX3000A\":\"74\"}},\r\n");
      out.write("\t\"xczxcb\":{\"dgasdg\":{\"asdgsdg\":\"83\",\"vczxvcx\":\"84\"},\"dgas\":{\"asdg\":\"83\",\"zxcvzxcv\":\"84\"},\"Lattice\":{\"MachXO\":\"79\",\"MachXO2\":\"80\",\"4000ZE\":\"78\"},\"Altera\":{\"MAXV\":\"76\",\"MAXII\":\"75\",\"MAX3000A\":\"74\"}},\r\n");
      out.write("\t\"xxcbsdg\":{\"dgasdg\":{\"asdgsdg\":\"83\",\"vczxvcx\":\"84\"},\"asdgdg\":{\"CoolRunner\":\"83\",\"zxcvzxcv\":\"84\"},\"Lattice\":{\"MachXO\":\"79\",\"MachXO2\":\"80\",\"4000ZE\":\"78\"},\"Altera\":{\"MAXV\":\"76\",\"MAXII\":\"75\",\"MAX3000A\":\"74\"}},\r\n");
      out.write("\t\"sggsa\":{\"dasggdc\":{\"dg\":\"83\",\"sdafawef\":\"84\"},\"Lattice\":{\"MachXO\":\"79\",\"MachXO2\":\"80\",\"4000ZE\":\"78\"},\"Altera\":{\"MAXV\":\"76\",\"MAXII\":\"75\",\"MAX3000A\":\"74\"}},\r\n");
      out.write("\t\"gegeg\":{\"zxccc\":{\"CoolRasdgadgunner\":\"83\",\"asefea\":\"84\"},\"Lattice\":{\"MachXO\":\"79\",\"MachXO2\":\"80\",\"4000ZE\":\"78\"},\"Altera\":{\"MAXV\":\"76\",\"MAXII\":\"75\",\"MAX3000A\":\"74\"}},\r\n");
      out.write("\t\"eg\":{\"rrrr\":{\"asdgdsag\":\"83\",\"adsgbdsg\":\"84\"},\"Lattice\":{\"MachXO\":\"79\",\"MachXO2\":\"80\",\"4000ZE\":\"78\"},\"Altera\":{\"MAXV\":\"76\",\"MAXII\":\"75\",\"MAX3000A\":\"74\"}},\r\n");
      out.write("\t\"ge\":{\"hhhh\":{\"ccc\":\"83\",\"ahghergya\":\"84\"},\"Lattice\":{\"MachXO\":\"79\",\"MachXO2\":\"80\",\"4000ZE\":\"78\"},\"dgasdg\":{\"asdgsdg\":\"83\",\"vczxvcx\":\"84\"},\"Altera\":{\"MAXV\":\"76\",\"MAXII\":\"75\",\"MAX3000A\":\"74\"}},\r\n");
      out.write("\t\"geg\":{\"nnnnn\":{\"asdg\":\"83\",\"abherh\":\"84\"},\"Lattice\":{\"MachXO\":\"79\",\"MachXO2\":\"80\",\"4000ZE\":\"78\"},\"Altera\":{\"MAXV\":\"76\",\"MAXII\":\"75\",\"MAX3000A\":\"74\"}},\r\n");
      out.write("\t\"geage\":{\"dagd\":{\"dsga\":\"83\",\"sgara\":\"84\"},\"Lattice\":{\"MachXO\":\"79\",\"MachXO2\":\"80\",\"4000ZE\":\"78\"},\"Altera\":{\"MAXV\":\"76\",\"MAXII\":\"75\",\"MAX3000A\":\"74\"}},\r\n");
      out.write("\t\"dfa\":{\"jjjj\":{\"CoocclRunner\":\"83\",\"sgaarg\":\"84\"},\"Lattice\":{\"MachXO\":\"79\",\"MachXO2\":\"80\",\"4000ZE\":\"78\"},\"Altera\":{\"MAXV\":\"76\",\"MAXII\":\"75\",\"MAX3000A\":\"74\"}},\r\n");
      out.write("\t\"adf\":{\"zcvzxc\":{\"CccoolRunner\":\"83\",\"fbaeaerh\":\"84\"},\"Lattice\":{\"MachXO\":\"79\",\"MachXO2\":\"80\",\"4000ZE\":\"78\"},\"Altera\":{\"MAXV\":\"76\",\"MAXII\":\"75\",\"MAX3000A\":\"74\"}},\r\n");
      out.write("\t\"daf\":{\"zzzz\":{\"CoolccRunner\":\"83\",\"asg\":\"84\"},\"Lattice\":{\"MachXO\":\"79\",\"MachXO2\":\"80\",\"4000ZE\":\"78\"},\"Altera\":{\"MAXV\":\"76\",\"MAXII\":\"75\",\"MAX3000A\":\"74\"}},\r\n");
      out.write("\t\"asdf\":{\"gggg\":{\"daf\":\"83\",\"adfasgasdg\":\"84\"},\"dgasdg\":{\"asdgsdg\":\"83\",\"vczxvcx\":\"84\"},\"Lattice\":{\"MachXO\":\"79\",\"MachXO2\":\"80\",\"4000ZE\":\"78\"},\"Altera\":{\"MAXV\":\"76\",\"MAXII\":\"75\",\"MAX3000A\":\"74\"}},\r\n");
      out.write("\t\"CD15\":{\"bbbb\":{\"dsaf\":\"83\",\"fbaf\":\"84\"},\"dgasdg\":{\"asdgsdg\":\"83\",\"vczxvcx\":\"84\"},\"Lattice\":{\"MachXO\":\"79\",\"MachXO2\":\"80\",\"4000ZE\":\"78\"},\"Altera\":{\"MAXV\":\"76\",\"MAXII\":\"75\",\"MAX3000A\":\"74\"}},\r\n");
      out.write("\t\"asdf\":{\"cvvvv\":{\"afds\":\"83\",\"dsg\":\"84\"},\"Lattice\":{\"MachXO\":\"79\",\"MachXO2\":\"80\",\"4000ZE\":\"78\"},\"Altera\":{\"MAXV\":\"76\",\"MAXII\":\"75\",\"MAX3000A\":\"74\"}},\r\n");
      out.write("\t\"asdf\":{\"vbbbb\":{\"asdf\":\"83\",\"XC9500XL\":\"84\"},\"Lattice\":{\"MachXO\":\"79\",\"MachXO2\":\"80\",\"4000ZE\":\"78\"},\"Altera\":{\"MAXV\":\"76\",\"MAXII\":\"75\",\"MAX3000A\":\"74\"}},\r\n");
      out.write("\t\"dadg\":{\"bbb\":{\"CoolRsdfsddafunner\":\"83\",\"XC9500XL\":\"84\"},\"Lattice\":{\"MachXO\":\"79\",\"MachXO2\":\"80\",\"4000ZE\":\"78\"},\"Altera\":{\"MAXV\":\"76\",\"MAXII\":\"75\",\"MAX3000A\":\"74\"}},\r\n");
      out.write("\t\"vdf\":{\"ffff\":{\"dsf\":\"83\",\"XC9500XL\":\"84\"},\"Lattice\":{\"MachXO\":\"79\",\"MachXO2\":\"80\",\"4000ZE\":\"78\"},\"Altera\":{\"MAXV\":\"76\",\"MAXII\":\"75\",\"MAX3000A\":\"74\"}},\r\n");
      out.write("\t\"eeaeg\":{\"zzzz\":{\"asdfdsfsa\":\"83\",\"XC9500XL\":\"84\"},\"Lattice\":{\"MachXO\":\"79\",\"MachXO2\":\"80\",\"4000ZE\":\"78\"},\"Altera\":{\"MAXV\":\"76\",\"MAXII\":\"75\",\"MAX3000A\":\"74\"}},\r\n");
      out.write("\t\"eadsg\":{\"aaa\":{\"dfdafdf\":\"83\",\"XC9500XL\":\"84\"},\"dgasdg\":{\"asdgsdg\":\"83\",\"vczxvcx\":\"84\"},\"Lattice\":{\"MachXO\":\"79\",\"MachXO2\":\"80\",\"4000ZE\":\"78\"},\"Altera\":{\"MAXV\":\"76\",\"MAXII\":\"75\",\"MAX3000A\":\"74\"}},\r\n");
      out.write("\t\"dgeae\":{\"ggg\":{\"dsfdsafds\":\"83\",\"XC9500XL\":\"84\"},\"Lattice\":{\"MachXO\":\"79\",\"MachXO2\":\"80\",\"4000ZE\":\"78\"},\"Altera\":{\"MAXV\":\"76\",\"MAXII\":\"75\",\"MAX3000A\":\"74\"}},\r\n");
      out.write("\t\"dasgdg\":{\"Xidddlinx\":{\"sadfdfassdf\":\"83\",\"XC9500XL\":\"84\"},\"Lattice\":{\"MachXO\":\"79\",\"MachXO2\":\"80\",\"4000ZE\":\"78\"},\"Altera\":{\"MAXV\":\"76\",\"MAXII\":\"75\",\"MAX3000A\":\"74\"}},\r\n");
      out.write("\t\"dasgdg\":{\"zzzz\":{\"fdwdaf\":\"83\",\"XC9500XL\":\"84\"},\"Lattice\":{\"MachXO\":\"79\",\"MachXO2\":\"80\",\"4000ZE\":\"78\"},\"Altera\":{\"MAXV\":\"76\",\"MAXII\":\"75\",\"MAX3000A\":\"74\"}},\r\n");
      out.write("\t\"bvd\":{\"zcvzcgr\":{\"eafef\":\"83\",\"XC9500XL\":\"84\"},\"dgasdg\":{\"asdgsdg\":\"83\",\"vczxvcx\":\"84\"},\"Lattice\":{\"MachXO\":\"79\",\"MachXO2\":\"80\",\"4000ZE\":\"78\"},\"Altera\":{\"MAXV\":\"76\",\"MAXII\":\"75\",\"MAX3000A\":\"74\"}},\r\n");
      out.write("\t\"gawe\":{\"Xigaegflinx\":{\"aefff\":\"83\",\"XC9500XL\":\"84\"},\"Lattice\":{\"MachXO\":\"79\",\"MachXO2\":\"80\",\"4000ZE\":\"78\"},\"Altera\":{\"MAXV\":\"76\",\"MAXII\":\"75\",\"MAX3000A\":\"74\"}},\r\n");
      out.write("\t\"asdg\":{\"aggag\":{\"asdfasdf\":\"83\",\"XC9500XL\":\"84\"},\"Lattice\":{\"MachXO\":\"79\",\"MachXO2\":\"80\",\"4000ZE\":\"78\"},\"Altera\":{\"MAXV\":\"76\",\"MAXII\":\"75\",\"MAX3000A\":\"74\"}},\r\n");
      out.write("\t\"aherh\":{\"agagdfg\":{\"cvdvaf\":\"83\",\"XC9500XL\":\"84\"},\"Lattice\":{\"MachXO\":\"79\",\"MachXO2\":\"80\",\"4000ZE\":\"78\"},\"Altera\":{\"MAXV\":\"76\",\"MAXII\":\"75\",\"MAX3000A\":\"74\"}},\r\n");
      out.write("\t\r\n");
      out.write("}");
      out.write("\r\n");
      out.write("\t);\r\n");
      out.write("\r\n");
      out.write("\tfunction searchSubmits() {\r\n");
      out.write("\t\tvar textvar = document.getElementById(\"typeName\").value;\r\n");
      out.write("\t\tif (textvar.length == 0 || !/^[a-zA-Z][a-zA-Z0-9]*$/.test(textvar)) {\r\n");
      out.write("\t\t\talert(\"please type in key words!\");\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tdocument.forms['nameSearch'].submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("</script>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"templatemo_main\">\r\n");
      out.write("\t\t\t<h2>Login</h2>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td style=\"background-color: #ECECEC;\" width=\"40%\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"loginform\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"margin-top: 50px; margin-bottom: 150px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<table style=\"margin-left: 50px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td width=\"63\">Username:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td width=\"350\"><input type=\"text\" id=\"usernametxt\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"padding-bottom: 5px; padding-top: 5px; margin-bottom: 5px; margin-top: 5px; width: 150px;\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td width=\"63\">Password:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td width=\"350\"><input type=\"password\" id=\"passwordtxt\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonclick=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"padding-bottom: 5px; padding-top: 5px; margin-bottom: 5px; margin-top: 5px; width: 150px;\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>Verify&nbsp;Code:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div style=\"height: 42px; width: 50px; float: left;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"verifycodetxt\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"width: 42px; height: 36px;\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div style=\"width: 100px; float: left;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img id=\"verifycodeimage\" width=\"100\" height=\"42\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tonclick=\"javascript:this.src='/account/verifyCode'\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"cursor: pointer;\" src=\"/account/verifyCode\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td colspan=\"3\">&nbsp;&nbsp;&nbsp;<a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thref=\"/forgotpassword\">Forgot your password?</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td width=\"63\"><input type=\"button\" name=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonclick=\"loginSubmit()\" value=\"Login\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td width=\"350\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td width=\"60%\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div id=\"registerlabel\" style=\"padding-left: 80px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"si-sp si-fl g-hlp si-fn\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<b>New in SymbolBox?</b>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<form action=\"\" method=\"post\" id=\"signinForm\" name=\"signinForm\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span> <input type=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonclick=\"window.location.href='/register'\" value=\"Register\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- END of templatemo_main -->\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"cleaner\"></div>\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("\t<div class=\"footernav\">\r\n");
      out.write("\t\t<p class=\"flcontent float_l\">\r\n");
      out.write("\t\t\tCopyright&copy; SymbolBox 2014.<br />All Service &copy; SymbolBox\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t<p class=\"frcontent float_r\">\r\n");
      out.write("\t\t\t<a href=\"/index\">Home</a> / <a href=\"#\">Support</a> / <a\r\n");
      out.write("\t\t\t\thref=\"#\">Terms and Conditions</a> / <a href=\"#\">Faqs</a> /<a\r\n");
      out.write("\t\t\t\thref=\"#\"> Contact us</a>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
