/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2015-01-01 07:13:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.ecommerce;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.sgnbs.system.beans.AdminBean;

public final class support_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/views/ecommerce/type.json", Long.valueOf(1420091663000L));
    _jspx_dependants.put("/WEB-INF/views/ecommerce/header_right.jsp", Long.valueOf(1420091663000L));
    _jspx_dependants.put("/WEB-INF/views/ecommerce/header.jsp", Long.valueOf(1420096423000L));
    _jspx_dependants.put("/WEB-INF/views/ecommerce/footer.jsp", Long.valueOf(1420091663000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<title>Software Store - Support</title>\r\n");
      out.write("<meta name=\"keywords\"\r\n");
      out.write("\tcontent=\"symbol box,software store, free template, ecommerce, online shop\" />\r\n");
      out.write("<meta name=\"description\"\r\n");
      out.write("\tcontent=\"symbol box,software store, free template, ecommerce, online shop \" />\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/css/ecommerce/default.css\" />\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/ecommerce/jquery-1.7.2.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"/js/ecommerce/jquery.flexslider-min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"wrap\">\r\n");
      out.write("\t\t");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"/css/ecommerce/top_menu.css\" />\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/ecommerce/getsidebarlist.js\"></script>\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("\t<div class=\"header_nav\">\r\n");
      out.write("\t\t<div class=\"left_logo float_l\"></div>\r\n");
      out.write("\t\t<div class=\"right_nav float_r\">\r\n");
      out.write("\t\t\t<div class=\"login-search\" id=\"header_right\">");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	response.setHeader("Cache-Control", "no-cache"); //HTTP 1.1 
	response.setHeader("Pragma", "no-cache"); //HTTP 1.0 
	response.setDateHeader("Expires", 0); //prevents caching at the proxy server 
	AdminBean adminBean = (AdminBean) session.getAttribute("adminBean");
	StringBuffer jsp = new StringBuffer("<ul>");
	if (adminBean != null) {
		String useradmin = adminBean.getUsername();
		jsp.append("<li>");
		jsp.append("Welcome back:");
		jsp.append(useradmin);
		jsp.append("</li>");
		jsp.append("<li><a href=\"/myaccount\">My Account</a></li>");
		jsp.append("<li><a href=\"/myaccount?menuname=mycart\">My Cart</a></li>");
		jsp.append("<li><a href=\"/account/exist_submit\">Safety exit</a></li>");
	} else {
		jsp.append("<li>Welcome to SymbolBox,Please <a href=\"/login\">Login</a> or <a href=\"/register\">Register</a></li>");
	}
	jsp.append("</ul>");
	out.println(jsp.toString());

      out.write('\r');
      out.write('\n');
      out.write("</div>\r\n");
      out.write("\t\t\t<div class=\"cleaner\"></div>\r\n");
      out.write("\t\t\t<div class=\"menu\" id=\"menu\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/index\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"top_menu_list item\" id=\"top_menu_list_products\"><a\r\n");
      out.write("\t\t\t\t\t\thref=\"/product/product/query_detail.action\">Products</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/ordersymbol\">Order symbol</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/designhouse\">Design House</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/support\">Support</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/aboutus\">About us</a></li>\r\n");
      out.write("\t\t\t\t\t<!-- <li style=\"width: 150px;\">\r\n");
      out.write("\t\t\t\t\t\t<form method=\"post\" action=\"/typeparam/typeparam/mod_valid.action\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"nameSearch\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:searchSubmits()\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"float: right; margin-top: 12px;\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"/images/ecommerce/icon_search.png\"></img></a> <input\r\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"text\" value=\"\" name=\"model.namelike\" id=\"typeName\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width: 120px; float: right; margin-top: 16px;\" />\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</li> -->\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"cleaner\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tgetTopList(\r\n");
      out.write("{\r\n");
      out.write("\t\"CPLD\":{\"Xilinx\":{\"CoolRunner\":\"83\",\"faefef\":\"84\"},\"dgasdg\":{\"asdgsdg\":\"83\",\"vczxvcx\":\"84\"},\"Lattice\":{\"MachXO\":\"79\",\"MachXO2\":\"80\",\"4000ZE\":\"78\"},\"dgasdg\":{\"asdgsdg\":\"83\",\"vczxvcx\":\"84\"},\"Altera\":{\"MAXV\":\"76\",\"MAXII\":\"75\",\"MAX3000A\":\"74\"}},\r\n");
      out.write("\t\"gagadg\":{\"gasggdag\":{\"eagawe\":\"83\",\"asdf\":\"84\",\"asdgsdg\":\"83\",\"vczxvcx\":\"84\"},\"Lattice\":{\"MachXO\":\"79\",\"MachXO2\":\"80\",\"4000ZE\":\"78\"},\"Altera\":{\"MAXV\":\"76\",\"MAXII\":\"75\",\"MAX3000A\":\"74\"}},\r\n");
      out.write("\t\"asdsdg\":{\"dgasdg\":{\"asdgsdg\":\"83\",\"vczxvcx\":\"84\"},\"Lattice\":{\"MachXO\":\"79\",\"MachXO2\":\"80\",\"4000ZE\":\"78\"},\"Altera\":{\"MAXV\":\"76\",\"MAXII\":\"75\",\"MAX3000A\":\"74\"}},\r\n");
      out.write("\t\"xczxcb\":{\"dgasdg\":{\"asdgsdg\":\"83\",\"vczxvcx\":\"84\"},\"dgas\":{\"asdg\":\"83\",\"zxcvzxcv\":\"84\"},\"Lattice\":{\"MachXO\":\"79\",\"MachXO2\":\"80\",\"4000ZE\":\"78\"},\"Altera\":{\"MAXV\":\"76\",\"MAXII\":\"75\",\"MAX3000A\":\"74\"}},\r\n");
      out.write("\t\"xxcbsdg\":{\"dgasdg\":{\"asdgsdg\":\"83\",\"vczxvcx\":\"84\"},\"asdgdg\":{\"CoolRunner\":\"83\",\"zxcvzxcv\":\"84\"},\"Lattice\":{\"MachXO\":\"79\",\"MachXO2\":\"80\",\"4000ZE\":\"78\"},\"Altera\":{\"MAXV\":\"76\",\"MAXII\":\"75\",\"MAX3000A\":\"74\"}},\r\n");
      out.write("\t\"sggsa\":{\"dasggdc\":{\"dg\":\"83\",\"sdafawef\":\"84\"},\"Lattice\":{\"MachXO\":\"79\",\"MachXO2\":\"80\",\"4000ZE\":\"78\"},\"Altera\":{\"MAXV\":\"76\",\"MAXII\":\"75\",\"MAX3000A\":\"74\"}},\r\n");
      out.write("\t\"gegeg\":{\"zxccc\":{\"CoolRasdgadgunner\":\"83\",\"asefea\":\"84\"},\"Lattice\":{\"MachXO\":\"79\",\"MachXO2\":\"80\",\"4000ZE\":\"78\"},\"Altera\":{\"MAXV\":\"76\",\"MAXII\":\"75\",\"MAX3000A\":\"74\"}},\r\n");
      out.write("\t\"eg\":{\"rrrr\":{\"asdgdsag\":\"83\",\"adsgbdsg\":\"84\"},\"Lattice\":{\"MachXO\":\"79\",\"MachXO2\":\"80\",\"4000ZE\":\"78\"},\"Altera\":{\"MAXV\":\"76\",\"MAXII\":\"75\",\"MAX3000A\":\"74\"}},\r\n");
      out.write("\t\"ge\":{\"hhhh\":{\"ccc\":\"83\",\"ahghergya\":\"84\"},\"Lattice\":{\"MachXO\":\"79\",\"MachXO2\":\"80\",\"4000ZE\":\"78\"},\"dgasdg\":{\"asdgsdg\":\"83\",\"vczxvcx\":\"84\"},\"Altera\":{\"MAXV\":\"76\",\"MAXII\":\"75\",\"MAX3000A\":\"74\"}},\r\n");
      out.write("\t\"geg\":{\"nnnnn\":{\"asdg\":\"83\",\"abherh\":\"84\"},\"Lattice\":{\"MachXO\":\"79\",\"MachXO2\":\"80\",\"4000ZE\":\"78\"},\"Altera\":{\"MAXV\":\"76\",\"MAXII\":\"75\",\"MAX3000A\":\"74\"}},\r\n");
      out.write("\t\"geage\":{\"dagd\":{\"dsga\":\"83\",\"sgara\":\"84\"},\"Lattice\":{\"MachXO\":\"79\",\"MachXO2\":\"80\",\"4000ZE\":\"78\"},\"Altera\":{\"MAXV\":\"76\",\"MAXII\":\"75\",\"MAX3000A\":\"74\"}},\r\n");
      out.write("\t\"dfa\":{\"jjjj\":{\"CoocclRunner\":\"83\",\"sgaarg\":\"84\"},\"Lattice\":{\"MachXO\":\"79\",\"MachXO2\":\"80\",\"4000ZE\":\"78\"},\"Altera\":{\"MAXV\":\"76\",\"MAXII\":\"75\",\"MAX3000A\":\"74\"}},\r\n");
      out.write("\t\"adf\":{\"zcvzxc\":{\"CccoolRunner\":\"83\",\"fbaeaerh\":\"84\"},\"Lattice\":{\"MachXO\":\"79\",\"MachXO2\":\"80\",\"4000ZE\":\"78\"},\"Altera\":{\"MAXV\":\"76\",\"MAXII\":\"75\",\"MAX3000A\":\"74\"}},\r\n");
      out.write("\t\"daf\":{\"zzzz\":{\"CoolccRunner\":\"83\",\"asg\":\"84\"},\"Lattice\":{\"MachXO\":\"79\",\"MachXO2\":\"80\",\"4000ZE\":\"78\"},\"Altera\":{\"MAXV\":\"76\",\"MAXII\":\"75\",\"MAX3000A\":\"74\"}},\r\n");
      out.write("\t\"asdf\":{\"gggg\":{\"daf\":\"83\",\"adfasgasdg\":\"84\"},\"dgasdg\":{\"asdgsdg\":\"83\",\"vczxvcx\":\"84\"},\"Lattice\":{\"MachXO\":\"79\",\"MachXO2\":\"80\",\"4000ZE\":\"78\"},\"Altera\":{\"MAXV\":\"76\",\"MAXII\":\"75\",\"MAX3000A\":\"74\"}},\r\n");
      out.write("\t\"CD15\":{\"bbbb\":{\"dsaf\":\"83\",\"fbaf\":\"84\"},\"dgasdg\":{\"asdgsdg\":\"83\",\"vczxvcx\":\"84\"},\"Lattice\":{\"MachXO\":\"79\",\"MachXO2\":\"80\",\"4000ZE\":\"78\"},\"Altera\":{\"MAXV\":\"76\",\"MAXII\":\"75\",\"MAX3000A\":\"74\"}},\r\n");
      out.write("\t\"asdf\":{\"cvvvv\":{\"afds\":\"83\",\"dsg\":\"84\"},\"Lattice\":{\"MachXO\":\"79\",\"MachXO2\":\"80\",\"4000ZE\":\"78\"},\"Altera\":{\"MAXV\":\"76\",\"MAXII\":\"75\",\"MAX3000A\":\"74\"}},\r\n");
      out.write("\t\"asdf\":{\"vbbbb\":{\"asdf\":\"83\",\"XC9500XL\":\"84\"},\"Lattice\":{\"MachXO\":\"79\",\"MachXO2\":\"80\",\"4000ZE\":\"78\"},\"Altera\":{\"MAXV\":\"76\",\"MAXII\":\"75\",\"MAX3000A\":\"74\"}},\r\n");
      out.write("\t\"dadg\":{\"bbb\":{\"CoolRsdfsddafunner\":\"83\",\"XC9500XL\":\"84\"},\"Lattice\":{\"MachXO\":\"79\",\"MachXO2\":\"80\",\"4000ZE\":\"78\"},\"Altera\":{\"MAXV\":\"76\",\"MAXII\":\"75\",\"MAX3000A\":\"74\"}},\r\n");
      out.write("\t\"vdf\":{\"ffff\":{\"dsf\":\"83\",\"XC9500XL\":\"84\"},\"Lattice\":{\"MachXO\":\"79\",\"MachXO2\":\"80\",\"4000ZE\":\"78\"},\"Altera\":{\"MAXV\":\"76\",\"MAXII\":\"75\",\"MAX3000A\":\"74\"}},\r\n");
      out.write("\t\"eeaeg\":{\"zzzz\":{\"asdfdsfsa\":\"83\",\"XC9500XL\":\"84\"},\"Lattice\":{\"MachXO\":\"79\",\"MachXO2\":\"80\",\"4000ZE\":\"78\"},\"Altera\":{\"MAXV\":\"76\",\"MAXII\":\"75\",\"MAX3000A\":\"74\"}},\r\n");
      out.write("\t\"eadsg\":{\"aaa\":{\"dfdafdf\":\"83\",\"XC9500XL\":\"84\"},\"dgasdg\":{\"asdgsdg\":\"83\",\"vczxvcx\":\"84\"},\"Lattice\":{\"MachXO\":\"79\",\"MachXO2\":\"80\",\"4000ZE\":\"78\"},\"Altera\":{\"MAXV\":\"76\",\"MAXII\":\"75\",\"MAX3000A\":\"74\"}},\r\n");
      out.write("\t\"dgeae\":{\"ggg\":{\"dsfdsafds\":\"83\",\"XC9500XL\":\"84\"},\"Lattice\":{\"MachXO\":\"79\",\"MachXO2\":\"80\",\"4000ZE\":\"78\"},\"Altera\":{\"MAXV\":\"76\",\"MAXII\":\"75\",\"MAX3000A\":\"74\"}},\r\n");
      out.write("\t\"dasgdg\":{\"Xidddlinx\":{\"sadfdfassdf\":\"83\",\"XC9500XL\":\"84\"},\"Lattice\":{\"MachXO\":\"79\",\"MachXO2\":\"80\",\"4000ZE\":\"78\"},\"Altera\":{\"MAXV\":\"76\",\"MAXII\":\"75\",\"MAX3000A\":\"74\"}},\r\n");
      out.write("\t\"dasgdg\":{\"zzzz\":{\"fdwdaf\":\"83\",\"XC9500XL\":\"84\"},\"Lattice\":{\"MachXO\":\"79\",\"MachXO2\":\"80\",\"4000ZE\":\"78\"},\"Altera\":{\"MAXV\":\"76\",\"MAXII\":\"75\",\"MAX3000A\":\"74\"}},\r\n");
      out.write("\t\"bvd\":{\"zcvzcgr\":{\"eafef\":\"83\",\"XC9500XL\":\"84\"},\"dgasdg\":{\"asdgsdg\":\"83\",\"vczxvcx\":\"84\"},\"Lattice\":{\"MachXO\":\"79\",\"MachXO2\":\"80\",\"4000ZE\":\"78\"},\"Altera\":{\"MAXV\":\"76\",\"MAXII\":\"75\",\"MAX3000A\":\"74\"}},\r\n");
      out.write("\t\"gawe\":{\"Xigaegflinx\":{\"aefff\":\"83\",\"XC9500XL\":\"84\"},\"Lattice\":{\"MachXO\":\"79\",\"MachXO2\":\"80\",\"4000ZE\":\"78\"},\"Altera\":{\"MAXV\":\"76\",\"MAXII\":\"75\",\"MAX3000A\":\"74\"}},\r\n");
      out.write("\t\"asdg\":{\"aggag\":{\"asdfasdf\":\"83\",\"XC9500XL\":\"84\"},\"Lattice\":{\"MachXO\":\"79\",\"MachXO2\":\"80\",\"4000ZE\":\"78\"},\"Altera\":{\"MAXV\":\"76\",\"MAXII\":\"75\",\"MAX3000A\":\"74\"}},\r\n");
      out.write("\t\"aherh\":{\"agagdfg\":{\"cvdvaf\":\"83\",\"XC9500XL\":\"84\"},\"Lattice\":{\"MachXO\":\"79\",\"MachXO2\":\"80\",\"4000ZE\":\"78\"},\"Altera\":{\"MAXV\":\"76\",\"MAXII\":\"75\",\"MAX3000A\":\"74\"}},\r\n");
      out.write("\t\r\n");
      out.write("}");
      out.write("\r\n");
      out.write("\t);\r\n");
      out.write("\r\n");
      out.write("\tfunction searchSubmits() {\r\n");
      out.write("\t\tvar textvar = document.getElementById(\"typeName\").value;\r\n");
      out.write("\t\tif (textvar.length == 0 || !/^[a-zA-Z][a-zA-Z0-9]*$/.test(textvar)) {\r\n");
      out.write("\t\t\talert(\"please type in key words!\");\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tdocument.forms['nameSearch'].submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("</script>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- END of templatemo_menubar -->\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"templatemo_main\">\r\n");
      out.write("\t\t\t<div id=\"content\" class=\"float_l faqs\">\r\n");
      out.write("\t\t\t\t<h1>Support</h1>\r\n");
      out.write("\t\t\t\t<h5>1. What we are selling</h5>\r\n");
      out.write("\t\t\t\t<p>SymbolBox strives to provide schematic symbols and PCB\r\n");
      out.write("\t\t\t\t\tfootprints of all mainstream IC components.All the IC components\r\n");
      out.write("\t\t\t\t\tare logically classified for your seaching.</p>\r\n");
      out.write("\t\t\t\t<p>The EDA tools that we are supporting are Cadence OrCAD,\r\n");
      out.write("\t\t\t\t\tMentor Graphics PADS ,CADSTAR Eagle and Altium designer.But we plan\r\n");
      out.write("\t\t\t\t\tto expand to all mainsteam tools. If you want</p>\r\n");
      out.write("\t\t\t\t<h5>2. How to pay</h5>\r\n");
      out.write("\t\t\t\t<p>Symbols or Footprints can be purchased by using the 'add to\r\n");
      out.write("\t\t\t\t\tcart' button which automatically takes you to your shopping cart\r\n");
      out.write("\t\t\t\t\twith that symbol or footprint, and you can buy multiple symbols by\r\n");
      out.write("\t\t\t\t\tclicking on 'continue shopping' or continue on to checkout by\r\n");
      out.write("\t\t\t\t\taccepting terms and conditions and clicking on 'checkout'. You can\r\n");
      out.write("\t\t\t\t\tview what symbols are in your shopping cart at any time by clicking\r\n");
      out.write("\t\t\t\t\ton the 'view cart' tab.</p>\r\n");
      out.write("\t\t\t\t<p>SymbolHome uses PayPal because the complete transaction is\r\n");
      out.write("\t\t\t\t\thandled by the PayPal secure server system and accepts many credit\r\n");
      out.write("\t\t\t\t\tcards. PayPal also handles conversion from any currency PayPal\r\n");
      out.write("\t\t\t\t\taccepts. PayPal is responsible for handling the credit card and\r\n");
      out.write("\t\t\t\t\tother payment details. Registration with PayPal is required if you\r\n");
      out.write("\t\t\t\t\tdon't already have a PayPal account.</p>\r\n");
      out.write("\t\t\t\t<h5>3. How to download</h5>\r\n");
      out.write("\t\t\t\t<p>After your paying for the symbols or Footprints, you will\r\n");
      out.write("\t\t\t\t\thave the ability to download purchased materials with your user\r\n");
      out.write("\t\t\t\t\tname and password. The purchased materials will be in your account\r\n");
      out.write("\t\t\t\t\tfor two months, you can download them at any time within ONE\r\n");
      out.write("\t\t\t\t\tmonths.</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<h5>4. Advices and questions</h5>\r\n");
      out.write("\t\t\t\t<p>Prompt a window to enable user to edit the advice and\r\n");
      out.write("\t\t\t\t\tquestions.</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<h5>5. Contact us</h5>\r\n");
      out.write("\t\t\t\t<p>Publish support@symbolbox.com</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"cleaner\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- END of templatemo_main -->\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"cleaner\"></div>\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("\t<div class=\"footernav\">\r\n");
      out.write("\t\t<p class=\"flcontent float_l\">\r\n");
      out.write("\t\t\tCopyright&copy; SymbolBox 2014.<br />All Service &copy; SymbolBox\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t<p class=\"frcontent float_r\">\r\n");
      out.write("\t\t\t<a href=\"/index\">Home</a> / <a href=\"#\">Support</a> / <a\r\n");
      out.write("\t\t\t\thref=\"#\">Terms and Conditions</a> / <a href=\"#\">Faqs</a> /<a\r\n");
      out.write("\t\t\t\thref=\"#\"> Contact us</a>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
